USE [master]
GO

/****** Object:  Database [ChatApp]    Script Date: 13.08.2021 17:12:36 ******/
DROP DATABASE [ChatApp]
GO

/****** Object:  Database [ChatApp]    Script Date: 13.08.2021 17:12:36 ******/
CREATE DATABASE [ChatApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ChatApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ChatApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ChatApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ChatApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ChatApp] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChatApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ChatApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ChatApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ChatApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ChatApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ChatApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [ChatApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ChatApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ChatApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ChatApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ChatApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ChatApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ChatApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ChatApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ChatApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ChatApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ChatApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ChatApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ChatApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ChatApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ChatApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ChatApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ChatApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ChatApp] SET RECOVERY FULL 
GO

ALTER DATABASE [ChatApp] SET  MULTI_USER 
GO

ALTER DATABASE [ChatApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ChatApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ChatApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ChatApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ChatApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ChatApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ChatApp] SET  READ_WRITE 
GO


